name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [18, 20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run -s lint

      - name: Test
        run: npm -s test

      - name: Smoke test migrations (SQLite)
        run: |
          node bin/migrate.js status
          node bin/migrate.js make ci_create_users_table
          node bin/migrate.js migrate
          node bin/migrate.js status
          node bin/migrate.js rollback --steps 1
          node bin/migrate.js status
